### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by abbliseng** [radial-color-picker/vue-color-picker#16]
**Describe the solution you'd like**
Hi, I would like to be able to change the color of the white space between the middle color and color wheel. I found that there was something posted around a solution but could not get it to work. Therefore I would like to request it'd be made a easy option, let's say a attribute you send with when using the component.

**Describe alternatives you've considered**
Alternately I would like a more direct and specific guide on how to modify it the current way within the css file.

**Comment by rkunev** [comment]
Since this was closed an hour after opening I'm assuming that you found out on your own how to change the color between the well (middle color) and the palette (color wheel/outer rainbow ring). 
You're right that there was a similar [question](https://github.com/radial-color-picker/vue-color-picker/issues/2#issuecomment-423836964) before, but for posterity, since the way to change the color changed, this is how to do it currently:
```css
.rcp__palette::before {
    /* any color works (transparent doesn't, sorry) */
    background-color: gold; 
}
```
