### ISSUE TITLE
Can't resolve '~@radial-color-picker/vue-color-picker/dist/vue-color-picker.min.css'

### ISSUE THREAD

**Issue by tsangaris** [radial-color-picker/vue-color-picker#18]
**Describe the bug**

After npm install the package i try to test it by copying the code in Github.

I get this error:

`Can't resolve '~@radial-color-picker/vue-color-picker/dist/vue-color-picker.min.css'`

By the way i am using **NuxtJS**.

Do i need to configure something in **nuxt.config.js**?

When i don't import the css then i get a page full page of colors. I assume that this is contained when the css is correctly imported into the page.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MACOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] latest

**Comment by rkunev** [comment]
Since you're using NuxtJS you can use the provided Nuxt module. You can find a complete example [here](https://github.com/radial-color-picker/vue-color-picker/tree/master/examples/with-nuxt), but here's a tl;dr:
1. [Add](https://github.com/radial-color-picker/vue-color-picker/blob/e5cd16054653961837da694226c7eefd37c7d7a5/examples/with-nuxt/nuxt.config.js#L14) the color picker Nuxt module to `nuxt.config.js`
2. [Use](https://github.com/radial-color-picker/vue-color-picker/blob/e5cd16054653961837da694226c7eefd37c7d7a5/examples/with-nuxt/pages/index.vue#L3) the color picker component as usual (no need to import the CSS yourself; the Nuxt module does that for you once for the whole app)

**Comment by tsangaris** [comment]
> Since you're using NuxtJS you can use the provided Nuxt module. You can find a complete example [here](https://github.com/radial-color-picker/vue-color-picker/tree/master/examples/with-nuxt), but here's a tl;dr:
> 
> 1. [Add](https://github.com/radial-color-picker/vue-color-picker/blob/e5cd16054653961837da694226c7eefd37c7d7a5/examples/with-nuxt/nuxt.config.js#L14) the color picker Nuxt module to `nuxt.config.js`
> 2. [Use](https://github.com/radial-color-picker/vue-color-picker/blob/e5cd16054653961837da694226c7eefd37c7d7a5/examples/with-nuxt/pages/index.vue#L3) the color picker component as usual (no need to import the CSS yourself; the Nuxt module does that for you once for the whole app)

Thanks @rkunev ! Any way to have the color picker start from the dot (minimized) instead from the dot and the ring around it? Also, how can i edit the size with css? Any clues?

**Comment by rkunev** [comment]
> Any way to have the color picker start from the dot (minimized) instead from the dot and the ring around it?

`:initially-collapsed="true"` will do the trick https://radial-color-picker.github.io/vue-color-picker/api.html#initially-collapsed

> Also, how can i edit the size with css? 

Nothing special here - just like you would change the width & height of other elements:
```vue
<template>
    <color-picker class="my-color-picker" />
</template>

<style>
.my-color-picker {
    width: 400px;
    height: 400px;
}
</style>
```
