### ISSUE TITLE
An error occurred while running on the real mobile terminal

### ISSUE THREAD

**Issue by xinmiti** [radial-color-picker/vue-color-picker#20]
20:56:20.761 [Vue warn]: Error in mounted hook: "ReferenceError: getComputedStyle is not defined"
20:56:20.824 found in
20:56:20.887 ---> <ColorPicker>
20:56:20.919 　　　　at pages/index/index.vue:1
20:56:20.951 ReferenceError: getComputedStyle is not defined

**Comment by rkunev** [comment]
[`getComputedStyle`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle#browser_compatibility) has been well supported since Internet Explorer 9 and as far back as Safari iOS 1 and WebView Android 1. Could you please provide more details what exactly is the real mobile terminal in your case?
